version: '3'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: 'sh /app/start-front.sh'
    volumes:
      - ./front:/app
    ports:
      - 8080:8080
