version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: 'sh /app/start-front.sh'
    tty: true
    volumes:
      - ./app:/app
      - ./wasm:/wasm
    ports:
      - 8080:8080
  wasm:
    build:
      context: ./wasm
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./wasm:/wasm
